[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chunk-loader = "ChUnQ7H46X5UeQJHVgZFBy3hGM95TwWsmvBRwQxVz3JG"

[programs.devnet]
chunk-loader = "ChUnQ7H46X5UeQJHVgZFBy3hGM95TwWsmvBRwQxVz3JG"

[test.validator]
warp_slot = 32

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 0 tests"
